# tmux.conf: minha configuração do tmux, o multiplexador de terminal clássico.
# Adiciona abas e splits em terminais sem essas funcionalidades, como o foot

set -s  escape-time        0
set -g  history-limit      5000
set -g  display-time       4000
set -g  status-interval    5
set -g  default-terminal   "${TERM}"
set -as terminal-overrides ",${TERM}*:Tc"
set -g  status-keys        emacs
set -g  mode-keys          vi
set -g  mouse              on
set -g  focus-events       on
set -wg aggressive-resize  on
set -g  allow-rename       off
set -g  renumber-windows   on
set -g  base-index         1
set -wg pane-base-index    1

# Esse encantamento misterioso faz com que os undercurls do neovim funcionem
# corretamente dentro do tmux, respeitando a cor do guisp. Fonte:
# https://www.reddit.com/r/neovim/comments/179tb2r/undercurl_in_tmuxneovim/
set -as terminal-overrides \
',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

#-------------------------------------------------------------------------------

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind C-p previous-window
bind C-n next-window
bind r   source-file "~/.config/tmux/tmux.conf"
bind a   last-window
bind c   new-window      -c "#{pane_current_path}"
bind h   split-window -v -c "#{pane_current_path}"
bind v   split-window -h -c "#{pane_current_path}"

bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1
bind -r C-h resize-pane -L 15
bind -r C-l resize-pane -R 15
bind -r C-k resize-pane -U 15
bind -r C-j resize-pane -D 15

bind j choose-window 'join-pane -b -h -s "%%"'
bind J choose-window 'join-pane -b -s "%%"'

#-------------------------------------------------------------------------------

set -g status-right       " #H │ %Y-%m-%d │ %H:%M "
set -g status-style       "bg=#333333 fg=#808080"
set -g status-left-style  "bg=#333333 fg=#ffffff"
set -g status-right-style "bg=#333333 fg=#ffffff"
set -g mode-style         "bg=#000000 fg=#ffffff"
set -g message-style      "bg=#000000 fg=#ffffff"

set -wg window-status-current-style "bg=#000000 fg=#c0c0c0"
set -wg window-status-current-format " #I:#W#{?window_flags,#{window_flags}, } "
