pad=2x0
font=Iosevka:size=12
# Pessoalmente, eu acho que as fontes ficam melhores com essa opção desligada
gamma-correct-blending=false

[key-bindings]
fullscreen=F11

[colors]
selection-foreground=e6e6e6
selection-background=839496

[csd]
size=23
color=FFAAAACC
border-width=1
