pad=2x0
shell=tmux
font=Hack:size=10
# Pessoalmente, eu acho que a fonte Hack fica mais agradável sem correção
# gama. Também é a maneira mais comum de ela ser renderizada no Linux.
gamma-correct-blending=false

[key-bindings]
fullscreen=F11

[colors]
selection-foreground=e6e6e6
selection-background=839496

[csd]
size=23
color=FFAAAACC
border-width=1
